### ISSUE TITLE
Color selector doesn't work

### ISSUE THREAD

**Issue by pjebs** [gen2brain/dlgs#1]
On macos 10.13.2, color selector doesn't work.

It doesn't show and the code execution stops at that point and doesn't go to the next line to evaluate the returned response.

**Comment by gen2brain** [comment]
I am unable to test Color() on macOS, in vmware it complains:
`Unable to create basic Accelerated OpenGL renderer.`

What happens when you execute this command in terminal, does it open color picker?
`osascript -e 'set T to choose color default color {255, 255, 255}'`

**Comment by pjebs** [comment]
It hangs and seems to do nothing.

**Comment by gen2brain** [comment]
That is bad, per documentation https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/PromptforaColor.html it should just work. 

I will try to find more information about that issue, maybe also to return ErrNotImplemented if I can not resolve it.

**Comment by gen2brain** [comment]
It is interesting that in Script Editor `choose color` works, I tried also to execute osascript with saved script from Script Editor but it still just hangs and waits.

**Comment by gen2brain** [comment]
Fixed, the key part was to `tell application "Finder"` or some app that is always on to `choose color`.
