### ISSUE TITLE
any way to make the dialog on top ?

### ISSUE THREAD

**Issue by hick** [gen2brain/dlgs#16]
I searched "top" in this repository, and found no tips,   any tips to control the dialog on the top?  thx

![image](https://user-images.githubusercontent.com/38886/85287328-aef46d00-b4c6-11ea-8a2d-c76f514e206c.png)

**Comment by gen2brain** [comment]
No, zenity/qarma and applescript/osascript cannot handle it. Probably is only possible for win32 UI, so that means no support will be added for that.

**Comment by hick** [comment]
thanks all the same,  I found that goqt can do such function
