### ISSUE TITLE
File picker returns an incorrect path for USB devices on Windows

### ISSUE THREAD

**Issue by philenius** [gen2brain/dlgs#20]
There's a bug when I use `.File()` to pick a directory. More specific: picking the root directory of a USB device always yields a corrupted path.

**Picking a sub-directory of a USB device:**
Picking a sub-directory on a USB device works as expected. Example:
![grafik](https://user-images.githubusercontent.com/9049899/103649099-32a31200-4f5e-11eb-9dc3-59cb7ff5e864.png)

The returned path is `F:\testDir` which is correct. ✔️ 

**Picking the root directory of a USB device:**
If I select the root directory on a USB device, then the returned path contains parts of the USB device name (in this case `SanDisk`). Example:
![grafik](https://user-images.githubusercontent.com/9049899/103652145-fa520280-4f62-11eb-8620-1d8b66e28353.png)

The returned path is `F:\isk (F:)` which is incorrect / doesn't even exist. ❌ I tried this with different names (renamed the USB device) and the error is always the same (e.g. renaming the USB device to `MyUSB` results in the path `F:\B (F:)`). 

On Linux, picking the root directory of a USB device works perfectly fine. So, this seems to be an issue which is related to Windows only. I couldn't trace back the error to its source. Although, I can see in the debugger that the property `displayName` of the struct `browseinfoW` in function `dirDialog()` in file `file_windows.go` contains this incorrect path. Could it be, that this issue is due to different responses from syscalls? It could be that the syscall for picking a directory returns a different value when a user picks the root of a USB device.

**Code:**
```go
package main

import (
	"fmt"

	"github.com/gen2brain/dlgs"
)

func main() {
	selectedDirectory, _, err := dlgs.File("Pick a directory", "", true)
	if err != nil {
		panic(err)
	}
	fmt.Printf("selected directory: %s", selectedDirectory)
}
```

**Comment by ncruces** [comment]
Try removing/commenting this line:
https://github.com/gen2brain/dlgs/blob/f2c7498414a6ebb230460b21d80b2af9e0d7d23e/file_windows.go#L90

And replacing:
https://github.com/gen2brain/dlgs/blob/f2c7498414a6ebb230460b21d80b2af9e0d7d23e/file_windows.go#L96

With:
```go
return stringFromUtf16Ptr(&buf[0]), true 
```

**Comment by philenius** [comment]
Thank you for your response, @ncruces. If I understood you correctly, then you suggested to change the function `dirDialog()` to look like this (?):

```go
// dirDialog displays directory dialog.
func dirDialog(title string) (string, bool) {
	var bi browseinfoW
	buf := make([]uint16, maxPath)

	t, _ := syscall.UTF16PtrFromString(title)

	bi.title = t
        // Commented this line
	// bi.displayName = &buf[0]
	bi.flags = bifEditBox | bifNewDialogStyle

	lpItem := shBrowseForFolder(&bi)
	ok := shGetPathFromIDList(lpItem, &buf[0])
	if ok {
                // Replaced this line
		//return stringFromUtf16Ptr(bi.displayName), true
		return stringFromUtf16Ptr(&buf[0]), true
	}

	return "", false
}
```

~~I don't understand why changing these two lines should make a difference? Nethertheless, I tried it with your changes and I still get an incorrect path when I select a USB device (same error as described in the first message of this issue).~~

Edit: my mistake, Go did not recompile the changes in my local copy of dlgs. It actually works! Now, I can select the root of USB devices as well as child directories of USB devices and dlgs returns the correct file / directory path. Would you mind explaining to me why passing the pointer directly to `stringFromUtf16Ptr` works? Can this pointer / buffer only be read once?

**Comment by ncruces** [comment]
My guess is that the `shGetPathFromIDList` is not writing the null terminator to `buf`.

So, because you're reusing the buffer for "display name" and the result ("full path"), you were getting `F:\` (the "full path") partially overwriting `ScanDisk (F:\)` (the "display name"). Or something like that.

The reason it only failed for root folders, is that the those are probably the only ones where "full path" is shorter than "display name". The fix works, because `buf` is zero initialized and big enough to hold the result (`MAX_PATH`) so `shGetPathFromIDList` not writing a null terminator should not be a problem. And I don't see a point in trying to get the "display name" any way?

If it does work (I didn't test it) please do a PR with the fix for @gen2brain to consider?

**Comment by philenius** [comment]
Thank you. I agree with you, the "display name" is not being used nor returned from this function, so it's useless.

**Comment by gen2brain** [comment]
@philenius Can I merge PR? I cannot test on Windows.

**Comment by ncruces** [comment]
I think so, yes. This is how I do it in my lib:
https://github.com/ncruces/zenity/blob/master/file_windows.go#L306

Also thanks, your code helped me a lot with the text entry dialog (and _will_ help me a lot with the list dialog)!

**Comment by philenius** [comment]
@gen2brain sorry for my delayed response, yes you can merge the PR (I see that you already did so, thank you). I can only prove that my changes work at least on my Windows 10 machine. Here's a GIF where I select the root of a USB device subsequently a child directory. Both use cases work as expected:

![dlgs](https://user-images.githubusercontent.com/9049899/113785724-fb4c2900-9737-11eb-9656-168fef2923d5.gif)
